### ISSUE TITLE
Хендлер "Архивирование должности"

### ISSUE THREAD

**Issue by Julia-Ishmuratova** [training-of-new-employees/qon#21]

**Comment by maarehet** [comment]
## Задача

Реализовать хендлер переноса должности в архив администратором.


## Требования к хендлеру

Обновить должность по id
*Хендлер:* `PATCH /api/v1/positions/update/{id}`

Хендлер доступен только администратору. Архивирование должностей возможно в рамках одной компании.
Архивироание происходит по id должности.

*Формат запроса:*

```wasm
PATCH /api/v1/positions/archived/{id} HTTP/1.1
Content-Type: application/json
...

{
    "id": "<id>",
    "archived": "<true>",
}
```

*Возможные коды ответа:*

- `200` — должность архивирована;
- `400` — неверный формат запроса;
- `403` — недостаточно прав доступа;
- `404` — должность не найдена;
- `500` — Внутренняя ошибка сервера.

**Comment by SurayaBakhishzade** [comment]
Нашли несколько багов:
https://app.qase.io/defect/QUICKON/view/9
https://app.qase.io/defect/QUICKON/view/10

**Comment by Nexadis** [comment]
Думаю данную ручку можно сделать частью обновления должности, т.к. по факту мы просто обновляем одно из полей сущности position. Либо просто архивировать с помощью запроса `DELETE /api/v1/positions/{id}`, сам метод DELETE явно укажет на наши намерения об удалении должности.  Во втором случае даже отпадает необходимость в передаче тела запроса.
Что думаете @Julia-Ishmuratova @kozyrev-m @SurayaBakhishzade ?

**Comment by kozyrev-m** [comment]
> Думаю данную ручку можно сделать частью обновления должности, т.к. по факту мы просто обновляем одно из полей сущности position. Либо просто архивировать с помощью запроса `DELETE /api/v1/positions/{id}`, сам метод DELETE явно укажет на наши намерения об удалении должности. Во втором случае даже отпадает необходимость в передаче тела запроса. Что думаете @Julia-Ishmuratova @kozyrev-m @SurayaBakhishzade ?

cfd

**Comment by kozyrev-m** [comment]
> Думаю данную ручку можно сделать частью обновления должности, т.к. по факту мы просто обновляем одно из полей сущности position. Либо просто архивировать с помощью запроса `DELETE /api/v1/positions/{id}`, сам метод DELETE явно укажет на наши намерения об удалении должности. Во втором случае даже отпадает необходимость в передаче тела запроса. Что думаете @Julia-Ishmuratova @kozyrev-m @SurayaBakhishzade ?

Может быть сделаем архивирование частью обновления?
Потому что если использовать DELETE для архивирования, то как будем поступать, если нам буквально понадобиться удалить объект?

**Comment by Nexadis** [comment]
Так много вопросов, и так мало ответов. Я сам не знаю почему мы не можем удалить, а архивируем. Вроде речи о восстановлении из архива не было, но если подумать, то обычно при удалении сущность переходит в состояние archived, а спустя какое-то время окончательно удаляется, а на протяжении времени в статусе archived её можно восстановить

**Comment by kozyrev-m** [comment]
> Так много вопросов, и так мало ответов. Я сам не знаю почему мы не можем удалить, а архивируем. Вроде речи о восстановлении из архива не было, но если подумать, то обычно при удалении сущность переходит в состояние archived, а спустя какое-то время окончательно удаляется, а на протяжении времени в статусе archived её можно восстановить

Если так рассуждать, то лучше тогда DELETE использовать.

**Comment by Nexadis** [comment]
В ТЗ написано следующее:
Чтобы восстановить пользователя из архива, необходимо нажать на иконку бургера и в выпадающем окне выбрать “Вернуть из архива”. Строка сотрудника в таблице становится снова активной.

**Comment by Nexadis** [comment]
С должностью таких пояснений нету

**Comment by Nexadis** [comment]
> > Думаю данную ручку можно сделать частью обновления должности, т.к. по факту мы просто обновляем одно из полей сущности position. Либо просто архивировать с помощью запроса `DELETE /api/v1/positions/{id}`, сам метод DELETE явно укажет на наши намерения об удалении должности. Во втором случае даже отпадает необходимость в передаче тела запроса. Что думаете @Julia-Ishmuratova @kozyrev-m @SurayaBakhishzade ?
> 
> Может быть сделаем архивирование частью обновления? Потому что если использовать DELETE для архивирования, то как будем поступать, если нам буквально понадобиться удалить объект?
> 
> Но у меня есть вопрос, который поможет нам определиться. Архивирование у нас для чего? Чтобы потом иметь возможность вернуть из архива? Или чтобы потом автоматически удалять записи со статусом "архив" по истечению какого-то времени?

Согласен с тем, что архивирование можно как часть обновления реализовать, согласно фигме при архивировании должности она не исчесзает а просто становится неактивной, но в списке должностей продолжает отображаться

**Comment by SurayaBakhishzade** [comment]
Всем привет! мне понравился запрос PATCH так как, это будет отличать функцию от того если мы будем именно удалять (может быть будет реализована в будущем)

**Comment by Lenamiroshnik** [comment]
баг:
https://app.qase.io/defect/QUICKON/view/47

**Comment by Nexadis** [comment]
@Lenamiroshnik У нас изменился способ архивирования должности, теперь мы это делаем через изменение должности, пример:
```bash
curl -X 'PATCH' \
  'http://localhost:8080/api/v1/positions/update/1' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "archived": true,
  "company_id": 0,
  "name": "string"
}'
```

**Comment by Lenamiroshnik** [comment]
Да архивирование происходит теперь 17.01.2024, 10:24, "Nexadis" ***@***.***>***@***.*** У нас изменился способ архивирования должности, теперь мы это делаем через изменение должности, пример:curl -X 'PATCH' \
  'http://localhost:8080/api/v1/positions/update/1' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "archived": true,
  "company_id": 0,
  "name": "string"
}'—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Lenamiroshnik** [comment]
Баг https://app.qase.io/defect/QUICKON/view/62

**Comment by Nexadis** [comment]
@Lenamiroshnik, привет, у нас архивирование это часть изменения данных о должности, ты в одном запросе меняешь должности как имя, так и его архивирование. Имя в запросе на изменении это новое желаемое имя, а вот привязка к конкретной должности идёт по её id. Это не баг, а бизнес-логика согласно требованиям

**Comment by Julia-Ishmuratova** [comment]
Таск по хендлеру закрыт, так как отдельный херндлер  для архивирования более не используется в проекте
