### ISSUE TITLE
(ЗАКРЫТЬ) Хендлеры прогресс сотрудника по курсу и урокам

### ISSUE THREAD

**Issue by Julia-Ishmuratova** [training-of-new-employees/qon#22]
Вместо этой задачи:
https://github.com/orgs/training-of-new-employees/projects/1/views/6?pane=issue&itemId=49551129
https://github.com/orgs/training-of-new-employees/projects/1/views/6?pane=issue&itemId=49856502
https://github.com/orgs/training-of-new-employees/projects/1/views/6?pane=issue&itemId=49855042

**Comment by kozyrev-m** [comment]
# Прогресса сотрудника по курсу

## Задача

Написать хендлер для получения прогресса по курсу.

Не нужно реализовывать метод для установки прогресса по курсу, так как прогресс по курсу определяется прогрессом по урокам курса.

У прогресса по курсу, так же как и по уроку, может быть 3 статуса:

- Не начат (not-started);
- В процессе (in-process);
- Пройден (done);

## Требования к хендлеру

*Хендлер:* `GET /api/v1/progress-course/get/{course-id}`

Хендлер доступен авторизованному сотруднику. В ответе должен содержаться прогресс сотрудника по курсу.

*Формат запроса:*

```wasm
GET /api/v1/progress-course/get/{course-id} HTTP/1.1
Content-Length: 0
```

*Возможные коды ответа:*

- `200` — запрос успешно обработан;
Формат ответа:

```wasm
{
		"id": 2
		"course_id": "<course_id>",
		"status": "<status>", // "not-started", "in-process", "done",
}
```

- `400` — неверный формат запроса;
- `401` — пользователь не авторизован.
- `404` — отсутствует курс или запись прогресса пользователя по курсу

**Comment by kozyrev-m** [comment]
# Прогресс сотрудника по урокам

## Задача

Написать хендлер для установки, получения прогресса по уроку.

У прогресса по уроку может быть 3 статуса:

- Не начат (not-started);
- В процессе (in-process);
- Пройден (done);

## Требования к хендлерам

### Установка прогресса по уроку

*Хендлер:* `POST/api/v1/progress-lesson/set`

Хендлер доступен сотруднику. В ответе должны содержаться данные установленного прогресса.

*Формат запроса:*

```wasm
POST /api/v1/progress-lesson/set HTTP/1.1
Content-Type: application/json

{
		"course_id": "<course_id>",
		"lesson_id": "<lesson_id>",
		"status": "<status>"       // "not-started", "in-process", "done"
}
```

*Возможные коды ответа:*

- `200` — статус успешно установлен;
Формат ответа:

```wasm
{
		"id": 2
		"course_id": "<course_id>",
		"lesson_id": "<lesson_id>",
		"status": "<status>", // "not-started", "in-process", "done",
}
```

- `400` — неверный формат запроса;
- `401` — пользователь не авторизован.
- `404` — отсутствует урок или прогресс пользователя по уроку
- `500` — внутренняя ошибка сервера.

### Получение прогресса по уроку

*Хендлер:* `GET /api/v1/progress-lesson/get/{lesson-id}`

Хендлер доступен авторизованному сотруднику. В ответе должен содержаться прогресс сотрудника по уроку.

*Формат запроса:*

```wasm
GET /api/v1/lesson/{id} HTTP/1.1
Content-Length: 0
```

*Возможные коды ответа:*

- `200` — запос успешно обработан;
Формат ответа:

```wasm
{
		"id": 2
		"course_id": "<course_id>",
		"lesson_id": "<lesson_id>",
		"status": "<status>", // "not-started", "in-process", "done",
}
```

- `400` — неверный формат запроса;
- `401` — пользователь не авторизован.
- `404` — отсутствует урок или запись прогресса пользователя по уроку
- `500` — внутренняя ошибка сервера.

**Comment by Nexadis** [comment]
Зачем постфиксы set и get, если намерения о действия четко выражает HTTP-метод?

**Comment by kozyrev-m** [comment]
@Nexadis, по твоему замечанию исправил url-ы хендлеров.
