### ISSUE TITLE
(ЗАКРЫТЬ) Хендлер "Архивирование курса"

### ISSUE THREAD

**Issue by Julia-Ishmuratova** [training-of-new-employees/qon#32]
## Задача

Реализовать хендлер архивирования курса администратором.

## Требования к хендлеру

*Хендлер:* `PATCH /api/v1/positions/archived/{id}`

Хендлер доступен только администратору. Архивирование курса возможно в рамках одной компании.
Архивирование происходит по id курса.

*Формат запроса:*

```wasm
PATCH /api/v1/positions HTTP/1.1
Content-Type: application/json
...

{
    "id": "<2>",
    "archived": "true"
}
```

*Возможные коды ответа:*

- `200` — курс архивирован;
- `400` — неверный формат запроса;
- `403` — недостаточно прав доступа;
- `404` — курс не найден;
- `500` — Внутренняя ошибка сервера.

**Comment by Nexadis** [comment]
Данная документация никак не относится к курсам. Переносить курсы в архив предлагаю в рамках модификации информации о курсе.

**Comment by Julia-Ishmuratova** [comment]
Таск по хендлеру закрыт, так как отдельный херндлер для архивирования более не используется в проекте
