### ISSUE TITLE
🔴 Нашли Баги.(есть дубль) Хендлер "Получение данных курсов" (Пользователь)

### ISSUE THREAD

**Issue by Julia-Ishmuratova** [training-of-new-employees/qon#96]
## Дублирует таск

ЭТО НЕ ДУБЛЬ:
https://github.com/orgs/training-of-new-employees/projects/1/views/6?pane=issue&itemId=49551129
Это хендлер для получения курсов сотрудником

Вот это дубль:
https://github.com/orgs/training-of-new-employees/projects/1/views/6?pane=issue&itemId=49604969

## Задача

Написать хендлер для получения данных пользователя.

## Описание

*Хендлер:* `GET /api/v1/users/courses`

Хендлер доступен авторизованным пользователям.

### Формат запроса

```wasm
GET /api/v1/users/courses HTTP/1.1
```

### Возможные коды ответа

- `200` — курсы получены (используется в том числе для пустого результата)

_Формат ответа:_

```wasm
[
  {
    "course_id": <course-id>,
    "name": "<course-name>",
    "description": "<description>"
  },
  ...
]
```
- `400` — неверный формат запроса
- `401` — пользователь не авторизован
- `403` — пользователь не имеет доступа к хендлеру
- `404` — курсов не найдено
- `500` — внутренняя ошибка сервера

_Формат ответа для ошибок:_

```wasm
{
  "error": "<error-message>" // текст ошибки
}
```

**Comment by MarikaAV** [comment]
баги:
https://app.qase.io/defect/DEMO/view/75
https://app.qase.io/defect/DEMO/view/76
